name: Running Code Coverage

# Runs on creation of pull request or once code has been pushed directly to main
on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2 
    # Sets up node and node version
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    # Installs npm to run coverage test
    - name: Install dependencies
      run: npm install
    # Installs the jsdom environment
    # Runs the test coverage command
    - name: Run the tests
      run: |
       npm i jest-environment-jsdom --save-dev
       npm test -- --coverage
