name: Node.js
on: [pull_request]
jobs:
  build:
    name: Review code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          yarn install
          yarn test
